-- Keep automatic follows out of Community in Action.
--
-- New dashboard users (and the Mobilize settings "Auto-follow" sync) follow every
-- user on public.mobilize_auto_follow_targets. Those follows are not social actions,
-- and a single sync run can push thousands of rows into community_activity, which
-- inflates the "Happening Now" (past 24 hours) counter.
--
-- Safe to run multiple times.

-- ---------------------------------------------------------------------------
-- Trigger: skip follows whose target is on the auto-follow whitelist
-- ---------------------------------------------------------------------------
create or replace function public.community_feed_on_follow()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.mobilize_auto_follow_targets t
    where t.user_id = new.following_id
  ) then
    return new;
  end if;

  perform public.community_feed_insert(
    'mobilize_user_follow',
    new.follower_id::text || ':' || new.following_id::text,
    'social_follow',
    public.community_feed_actor_name(new.follower_id) || ' started following ' ||
      public.community_feed_actor_name(new.following_id),
    'Social Connections',
    null,
    'person',
    new.follower_id,
    new.created_at
  );
  return new;
end;
$$;

drop trigger if exists community_feed_follow on public.mobilize_user_follows;
create trigger community_feed_follow
after insert on public.mobilize_user_follows
for each row execute function public.community_feed_on_follow();

-- ---------------------------------------------------------------------------
-- Cleanup: drop feed rows already generated by auto-follow
-- ---------------------------------------------------------------------------
delete from public.community_activity ca
using public.mobilize_auto_follow_targets t
where ca.source_type = 'mobilize_user_follow'
  and split_part(ca.source_id, ':', 2) = t.user_id::text;
